"""Non-destructive timeline models — reference existing assets only."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import Field, field_validator

from src.models.base import StrictModel


def _utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:10]}"


class TrackKind(str, Enum):
    VIDEO = "video"
    VOICE = "voice"
    MUSIC = "music"
    SFX = "sfx"
    SUBTITLES = "subtitles"


class TransitionType(str, Enum):
    CUT = "cut"
    FADE = "fade"
    DISSOLVE = "dissolve"
    SLIDE = "slide"


class ExportAspect(str, Enum):
    LANDSCAPE = "16:9"
    PORTRAIT = "9:16"
    SQUARE = "1:1"


class ExportFormat(str, Enum):
    MP4 = "mp4"


class ExportJobStatus(str, Enum):
    QUEUED = "queued"
    PROCESSING = "processing"
    READY = "ready"
    FAILED = "failed"


class TimelineClip(StrictModel):
    """One clip on a track. References media; never owns generated bytes."""

    id: str = Field(default_factory=lambda: _new_id("clip"))
    label: str = ""
    scene_id: int | None = Field(default=None, ge=1)
    asset_id: int | None = Field(default=None, ge=1)
    media_url: str | None = None
    poster_url: str | None = None
    start_seconds: float = Field(default=0.0, ge=0.0)
    duration_seconds: float = Field(default=1.0, gt=0.0)
    in_point: float = Field(default=0.0, ge=0.0)
    out_point: float = Field(default=1.0, gt=0.0)
    source_duration: float = Field(default=1.0, gt=0.0)
    transition_in: TransitionType = TransitionType.CUT
    transition_out: TransitionType = TransitionType.CUT
    transition_duration: float = Field(default=0.0, ge=0.0)
    muted: bool = False
    text: str | None = None

    @field_validator("label", mode="before")
    @classmethod
    def _normalize_label(cls, value: object) -> object:
        if isinstance(value, str):
            return " ".join(value.split())
        return value

    @field_validator("media_url", "poster_url", "text", mode="before")
    @classmethod
    def _normalize_optional_strings(cls, value: object) -> object:
        if value is None:
            return None
        if isinstance(value, str):
            cleaned = " ".join(value.split())
            return cleaned or None
        return value

    @property
    def end_seconds(self) -> float:
        return self.start_seconds + self.duration_seconds

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json")


class TimelineTrack(StrictModel):
    id: str = Field(default_factory=lambda: _new_id("track"))
    kind: TrackKind
    name: str
    clips: list[TimelineClip] = Field(default_factory=list)
    locked: bool = False
    muted: bool = False
    height: int = Field(default=56, ge=32, le=160)

    @field_validator("name", mode="before")
    @classmethod
    def _normalize_name(cls, value: object) -> object:
        if isinstance(value, str):
            return " ".join(value.split())
        return value

    def clip_by_id(self, clip_id: str) -> TimelineClip:
        for clip in self.clips:
            if clip.id == clip_id:
                return clip
        raise KeyError(f"Clip {clip_id!r} not found on track {self.id}")

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json")


class ExportJob(StrictModel):
    """Queued render request — does not perform encoding in-process."""

    id: str = Field(default_factory=lambda: _new_id("export"))
    format: ExportFormat = ExportFormat.MP4
    aspect: ExportAspect = ExportAspect.LANDSCAPE
    status: ExportJobStatus = ExportJobStatus.QUEUED
    created_at: str = Field(default_factory=_utc_iso)
    updated_at: str = Field(default_factory=_utc_iso)
    message: str = "Queued for MP4 encode"
    output_path: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json")


class Timeline(StrictModel):
    """Project timeline document (non-destructive edit state)."""

    project_id: str
    version: int = Field(default=1, ge=1)
    tracks: list[TimelineTrack] = Field(default_factory=list)
    export_queue: list[ExportJob] = Field(default_factory=list)
    playhead_seconds: float = Field(default=0.0, ge=0.0)
    created_at: str = Field(default_factory=_utc_iso)
    updated_at: str = Field(default_factory=_utc_iso)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("project_id", mode="before")
    @classmethod
    def _normalize_project_id(cls, value: object) -> object:
        if isinstance(value, str):
            return " ".join(value.split())
        return value

    @property
    def duration_seconds(self) -> float:
        ends = [0.0]
        for track in self.tracks:
            for clip in track.clips:
                ends.append(clip.end_seconds)
        return max(ends)

    def track_by_id(self, track_id: str) -> TimelineTrack:
        for track in self.tracks:
            if track.id == track_id:
                return track
        raise KeyError(f"Track {track_id!r} not found")

    def track_by_kind(self, kind: TrackKind) -> TimelineTrack | None:
        for track in self.tracks:
            if track.kind == kind:
                return track
        return None

    def find_clip(self, clip_id: str) -> tuple[TimelineTrack, TimelineClip]:
        for track in self.tracks:
            for clip in track.clips:
                if clip.id == clip_id:
                    return track, clip
        raise KeyError(f"Clip {clip_id!r} not found")

    def touch(self) -> Timeline:
        return self.model_copy(
            update={
                "updated_at": _utc_iso(),
                "version": self.version + 1,
            }
        )

    def to_dict(self) -> dict[str, Any]:
        payload = self.model_dump(mode="json")
        payload["duration_seconds"] = self.duration_seconds
        return payload

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Timeline:
        payload = dict(data)
        payload.pop("duration_seconds", None)
        return cls.model_validate(payload)


def default_tracks() -> list[TimelineTrack]:
    """Standard Arahus track layout."""
    return [
        TimelineTrack(kind=TrackKind.VIDEO, name="Video", height=72),
        TimelineTrack(kind=TrackKind.VOICE, name="Voice", height=48),
        TimelineTrack(kind=TrackKind.MUSIC, name="Music", height=48),
        TimelineTrack(kind=TrackKind.SFX, name="SFX", height=48),
        TimelineTrack(kind=TrackKind.SUBTITLES, name="Subtitles", height=40),
    ]
